name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.server_url == 'https://github.com'
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - run: nvim --version
      - run: bash tests/run.sh
